name = "multi-wheel"
pages_build_output_dir = "./.svelte-kit/cloudflare"
compatibility_date = "2024-07-01"

# Run `pnpm wrangler d1 create <name>` before deploying!
[[d1_databases]]
binding = "DB"
database_name = ""
database_id = "<DATABASE_ID>"
